### ISSUE TITLE
Probability does not keep decreasing as murlocs in graveyard go above 7

### ISSUE THREAD

**Issue by nolmach** [numbers1311407/anyfin#1]
For example, if I have 1 bluegill warrior, and 6 non-charging murlocs in the graveyard, we get 100% chance of pulling the bluegill from the graveyard and dealing 2 damage (+ any bonuses from other murlocs).  As the number of non charging murlocs in the graveyard increases, we should see that the probability of pulling the bluegill from the graveyard decreases, but it does not.

**Comment by numbers1311407** [comment]
I believe this should have been fixed by 9b8c83a.

The probabilities not only didn't go up beyond 7 (or number of empty board slots) of each murloc type, they were also based only on unique combinations.  This actually affected average as well.

9b8c83a does 2 things.  It removes the limit of only calculating for enough of each murloc to fill the board (which fixes this specific issue), and it also tracks the number of times each damage total is seen and incorporates that into the probabilities & average.

I _think_ it's correct, but I haven't done any extended math on it (tried to sqeeze an emergency bug fix during the work day here).  I'll revisit it if it's still not correct.
